import assert from 'node:assert/strict';
import { test } from 'node:test';
import fs from 'node:fs';
import ts from 'typescript';
const compiledModule = { exports: {} };
new Function('module','exports',ts.transpileModule(fs.readFileSync('src/lib/health/scene-model.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(compiledModule,compiledModule.exports);
const {validateSketch,exampleSketch}=compiledModule.exports;
test('example is valid and cloned',()=>{ const copy=validateSketch(exampleSketch); assert.deepEqual(copy,exampleSketch); assert.notEqual(copy,exampleSketch); });
test('untrusted executable and remote properties rejected',()=>{ for(const field of ['script','url','texture']) {const scene=structuredClone(exampleSketch);scene.objects[0][field]='https://example.com';assert.throws(()=>validateSketch(scene));} });
test('bounds reject GPU abuse and invalid transforms',()=>{for(const value of [NaN,Infinity,-1,0,100]) {const scene=structuredClone(exampleSketch);scene.objects[0].scale[0]=value;assert.throws(()=>validateSketch(scene));} const scene=structuredClone(exampleSketch);scene.objects=Array(25).fill(scene.objects[0]);assert.throws(()=>validateSketch(scene)); });
test('invalid shapes, vectors, colors and labels rejected',()=>{for(const [key,value] of [['shape','mesh'],['position',[1,2]],['color','red']]) {const scene=structuredClone(exampleSketch);scene.objects[0][key]=value;assert.throws(()=>validateSketch(scene));} assert.throws(()=>validateSketch({...exampleSketch,title:''})); });
