"use client";
import { useRef, useState } from 'react';
import { SESSION_EFFORTS, type SessionFeedback } from '@/lib/health/training-feedback';
export default function TrainingFeedback({ feedback, today, busy, readOnly, onSave }: { feedback?:SessionFeedback; today:string; busy:boolean; readOnly:boolean; onSave:(feedback?:SessionFeedback)=>Promise<boolean> }) {
 const [editing,setEditing]=useState(!feedback),[effort,setEffort]=useState<SessionFeedback['effort']|''>(feedback?.effort??''),[note,setNote]=useState(feedback?.note??''),[saving,setSaving]=useState(false);
 const pending=useRef(false),heading=useRef<HTMLHeadingElement>(null);
 async function save(next?:SessionFeedback){if(busy||pending.current)return;pending.current=true;setSaving(true);try{if(await onSave(next)){setEditing(false);requestAnimationFrame(()=>heading.current?.focus());}}finally{pending.current=false;setSaving(false);}}
 if(readOnly&&!feedback)return null;
 return <section className="session-feedback" aria-label="Session reflection"><span className="eyebrow">YOUR REFLECTION</span><h4 ref={heading} tabIndex={-1}>How did it feel?</h4>
 {(!editing||readOnly)?<>{feedback?<><p className="session-feedback-effort">{feedback.effort} effort <span>· {feedback.updatedOn}</span></p>{feedback.note&&<p className="session-feedback-note">{feedback.note}</p>}</>:<p>No reflection saved.</p>}{!readOnly&&<button disabled={busy||saving} className="quiet-button" onClick={()=>{setEffort(feedback?.effort??'');setNote(feedback?.note??'');setEditing(true);requestAnimationFrame(()=>heading.current?.focus());}}>{feedback?'Edit reflection':'Add a reflection'}</button>}</>:<form onSubmit={e=>{e.preventDefault();if(effort)void save({effort,note,updatedOn:today});}}><fieldset disabled={busy||saving} className="plan-fields"><div className="feedback-efforts" role="group" aria-label="Perceived effort">{SESSION_EFFORTS.map(value=><button key={value} type="button" aria-pressed={effort===value} onClick={()=>setEffort(value)}>{value}</button>)}</div><label>Anything to remember? <span>(optional)</span><textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={280} rows={3} placeholder="What felt good, or what made it harder?"/></label><p className="plan-hint">{note.length}/280 · Saved with this session and available as context to your agent. This does not change your training plan.</p><div className="plan-actions"><button className="primary" disabled={!effort} type="submit">{saving?'Saving…':'Save reflection'}</button><button className="quiet-button" type="button" onClick={()=>{setEditing(false);requestAnimationFrame(()=>heading.current?.focus());}}>Cancel</button>{feedback&&<button className="quiet-button" type="button" onClick={()=>void save(undefined)}>Remove reflection</button>}</div></fieldset></form>}
 </section>;
}
